# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: jademichel
  password: 
  host: localhost

development:
  <<: *default
  database: the_gossip_project_development

test:
  <<: *default
  database: the_gossip_project_test

production:
  <<: *default
  database: the_gossip_project_production

